# Generated by Django 3.1.1 on 2020-11-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=20)),
                ('timeOpen', models.CharField(max_length=20)),
                ('timeClose', models.CharField(max_length=20)),
                ('timeZone', models.CharField(max_length=20)),
                ('marketCap', models.FloatField()),
                ('price', models.FloatField()),
                ('changePercent', models.FloatField()),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
