# Generated by Django 3.1.1 on 2020-11-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
